### ISSUE TITLE
1.5 last commit has memory leak

### ISSUE THREAD

**Issue by rampageX** [troglobit/mini-snmpd#17]
From `htop`, first two number as `VURT` - `RES` :

1.4 （very stable）：
![1 4-memory](https://user-images.githubusercontent.com/994081/73823338-fe494200-4832-11ea-9251-4bd18ec24aff.gif)

1.5 （keep grow）：
![1 5-mem](https://user-images.githubusercontent.com/994081/73823385-13be6c00-4833-11ea-993c-7b595ab8196e.gif)

**Comment by troglobit** [comment]
Thanks for the heads-up!  I'll have a look with valgrind tomorrow

**Comment by troglobit** [comment]
There, fixed! :)
