### ISSUE TITLE
Help in implementing SET commands

### ISSUE THREAD

**Issue by fraviofii** [troglobit/mini-snmpd#21]
Looking at the code, I saw that the SET implemetation is not supported.

I can understand that.

But, is there any guideline that I could follow to implement that?

**Comment by troglobit** [comment]
The whole point of mini-snmpd was to be small and simple.  That being said, I have no problem merging support for SET, but I cannot really set aside time to help you. Hope you understand, this is a very low-priority project for me.  I just picked it up because the original maintainer went awol ...

**Comment by fraviofii** [comment]
I studied the code and it is not evident to implement set commands.

First it must be implemented a strategy to capture the data that comes from the request. Some current functions can be used, but a specific structure to receive it must be implemented.

Then, during the specific set command, it must have a link to a function similar to that located  at utils.c. But, to implement that, a map between the oid and the function must me implemented.

It is very hard to do that in a generic way. And I can't imagine a simple implementation.

I am closing the issue.
