### ISSUE TITLE
linux.c/<ifaddrs.h> broken compatibility with arm

### ISSUE THREAD

**Issue by negan07** [troglobit/mini-snmpd#24]
the latest versions 1.5 & 1.6 can break compatibility with some arm devices due to `getifaddrs() ` function miss
had to rollback some code with previous `socket()` & `ioctl()` usage
[mini-snmpd-1.6-002-linux_reverting_ifaddrs_lib_usage.zip](https://github.com/troglobit/mini-snmpd/files/5720161/mini-snmpd-1.6-002-linux_reverting_ifaddrs_lib_usage.zip)
hoping this can help some users

**Comment by troglobit** [comment]
Not sure what to do with this.  It's nothing I can merge and the issue itself is not really related to "arm devices", but rather missing or not working `getifaddrs()` in the operating system.  More specifically the C-library.  I'm guessing your system is an embedded one, which makes it likely use one of the smaller C-libs, like uClibc or musl libc.  Both have had issues with `getifaddrs()` in the past.  This type of version matching of components is one of the most tedious things when composing a working system. 

I'm going to close this, future users can still find it googling, but I cannot justify keeping this an open issue against current mini-snmpd.
