### ISSUE TITLE
Add support for privilige separation

### ISSUE THREAD

**Issue by troglobit** [troglobit/mini-snmpd#6]
For increased security it would be beneficial to mini-snmpd if it supported `--priv-sep`.  Where a forked-off child runs the main (possibly Internet-facing) daemon part with dropped privileges and the parent remains with root privileges communicating `statfs()` results and the likes to the daemon over a UNIX domain socket.

This is quite a lot of work.

**Comment by hojuruku** [comment]
That init script I shared before is getting a rewrite.

Openwrt has a new mostly undocumented api for doing configuration for
daemons. My init script will check statfs() will work for the user the
daemon runs as on the mountpoints when it loads. If that helps.

I'll push the changes to my git in a few hours. The other option is if
seccomp filters are supported by default and takes of in openwrt as the
poor mans nsa secure linux for daemons you wont need to do any work.

**Comment by troglobit** [comment]
Basic support implemented in 9907cd5, thanks to NDM Systems.
